name: db_auto

on:
  schedule:
    - cron: "0 * * * *"  # Scheduled to run every hour for testing purposes
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specifies the runner environment

    env:
      CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      TEAM_ID: ${{ secrets.TEAM_ID }}

    steps:
      - uses: actions/checkout@v2  # Checks-out your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python environment
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run Python Script
        run: python scripts/db.py
